--------------------------------------------------------
--  Fichier créé - mercredi-avril-07-2021   
--------------------------------------------------------
DROP TABLE "ARIJ"."ABONNES" cascade constraints;
DROP TABLE "ARIJ"."BIBLIOTHEQUE" cascade constraints;
DROP TABLE "ARIJ"."COMMANDE" cascade constraints;
DROP TABLE "ARIJ"."CONGE" cascade constraints;
DROP TABLE "ARIJ"."EMPLOYE" cascade constraints;
DROP TABLE "ARIJ"."EVENEMENT" cascade constraints;
DROP TABLE "ARIJ"."FACTURES" cascade constraints;
DROP TABLE "ARIJ"."FOURNISSEURS" cascade constraints;
DROP TABLE "ARIJ"."HISTORIQUE" cascade constraints;
DROP TABLE "ARIJ"."JOUEURS" cascade constraints;
DROP TABLE "ARIJ"."PARTIES" cascade constraints;
DROP TABLE "ARIJ"."PRODUITS" cascade constraints;
DROP TABLE "ARIJ"."SEANCES" cascade constraints;
DROP TABLE "ARIJ"."TICKET" cascade constraints;
--------------------------------------------------------
--  DDL for Table ABONNES
--------------------------------------------------------

  CREATE TABLE "ARIJ"."ABONNES" 
   (	"CIN_ABONNES" VARCHAR2(20 BYTE), 
	"EMAIL_ABONNES" VARCHAR2(20 BYTE), 
	"NOM_ABONNES" VARCHAR2(20 BYTE), 
	"PRENOM_ABONNES" VARCHAR2(20 BYTE), 
	"TEL_ABONNES" VARCHAR2(20 BYTE), 
	"DDN_ABONNES" VARCHAR2(20 BYTE), 
	"TYPE_ABONEMENT" VARCHAR2(20 BYTE), 
	"SEXE" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table BIBLIOTHEQUE
--------------------------------------------------------

  CREATE TABLE "ARIJ"."BIBLIOTHEQUE" 
   (	"ID_L" NUMBER, 
	"NOM_L" VARCHAR2(20 BYTE), 
	"REF_LIVRE" VARCHAR2(20 BYTE), 
	"COLUMN1" VARCHAR2(20 BYTE), 
	"DATE_S" VARCHAR2(20 BYTE), 
	"DATE_R" VARCHAR2(20 BYTE), 
	"DISPL" VARCHAR2(20 BYTE), 
	"DISPL1" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table COMMANDE
--------------------------------------------------------

  CREATE TABLE "ARIJ"."COMMANDE" 
   (	"ID_COMMANDE" NUMBER, 
	"NB_PRODUIT" NUMBER, 
	"PRIX_T" FLOAT(126), 
	"COLUMN1" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CONGE
--------------------------------------------------------

  CREATE TABLE "ARIJ"."CONGE" 
   (	"ID" VARCHAR2(20 BYTE), 
	"NOMEMPLOYE" VARCHAR2(20 BYTE), 
	"DATED" VARCHAR2(20 BYTE), 
	"DATEF" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMPLOYE
--------------------------------------------------------

  CREATE TABLE "ARIJ"."EMPLOYE" 
   (	"ID" VARCHAR2(20 BYTE), 
	"NOM" VARCHAR2(20 BYTE), 
	"NUM" VARCHAR2(20 BYTE), 
	"MAIL" VARCHAR2(20 BYTE), 
	"DATEAD" VARCHAR2(20 BYTE), 
	"SEXE" VARCHAR2(20 BYTE), 
	"FEDERATION" VARCHAR2(20 BYTE), 
	"SALAIRE" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EVENEMENT
--------------------------------------------------------

  CREATE TABLE "ARIJ"."EVENEMENT" 
   (	"ID" VARCHAR2(20 BYTE), 
	"NOM" VARCHAR2(20 BYTE), 
	"COLUMN1" VARCHAR2(20 BYTE), 
	"COLUMN2" NUMBER, 
	"COLUMN3" NUMBER, 
	"COLUMN4" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FACTURES
--------------------------------------------------------

  CREATE TABLE "ARIJ"."FACTURES" 
   (	"ID_FACTURE" NUMBER, 
	"ID_FOURNISSEUR_FACTURE" NUMBER, 
	"TOTAL_FACTURE" FLOAT(126), 
	"ID_PRODUIT_FACTURE" NUMBER, 
	"DATE_FACTURE" DATE, 
	"ETAT_FACTURE" VARCHAR2(20 BYTE), 
	"QUANTITE_FACTURE" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FOURNISSEURS
--------------------------------------------------------

  CREATE TABLE "ARIJ"."FOURNISSEURS" 
   (	"ID_FOURNISSEUR" NUMBER, 
	"NOM_FOURNISSEUR" VARCHAR2(100 BYTE), 
	"ADRESSE_FOURNISSEUR" VARCHAR2(20 BYTE), 
	"TELEPHONE_FOURNISSEUR" VARCHAR2(20 BYTE), 
	"EMAIL_FOURNISSEUR" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table HISTORIQUE
--------------------------------------------------------

  CREATE TABLE "ARIJ"."HISTORIQUE" 
   (	"ID_COMMANDE" NUMBER, 
	"NOM_C" VARCHAR2(20 BYTE), 
	"PRODUIT_C" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table JOUEURS
--------------------------------------------------------

  CREATE TABLE "ARIJ"."JOUEURS" 
   (	"ID_JOUEUR" NUMBER, 
	"NOM_JOUEUR" VARCHAR2(20 BYTE), 
	"PRENOM_JOUEUR" VARCHAR2(20 BYTE), 
	"VILLE_JOUEUR" VARCHAR2(20 BYTE), 
	"DN_JOUEUR" DATE, 
	"EMAIL_JOUEUR" VARCHAR2(20 BYTE), 
	"TEL_JOUEUR" NUMBER, 
	"CLASSEMENT_ELO" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PARTIES
--------------------------------------------------------

  CREATE TABLE "ARIJ"."PARTIES" 
   (	"ID_PARTIE" NUMBER, 
	"CADENCE" VARCHAR2(20 BYTE), 
	"ID_NOIR" NUMBER, 
	"ID_BLANC" NUMBER, 
	"DEBUT_PARTIE" DATE, 
	"FIN_PARTIE" DATE, 
	"GAGNANT_PARTIE" VARCHAR2(20 BYTE), 
	"NUM_TABLE" NUMBER, 
	"COM_PARTIE" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PRODUITS
--------------------------------------------------------

  CREATE TABLE "ARIJ"."PRODUITS" 
   (	"ID_PRODUIT" NUMBER, 
	"NOM_PRODUIT" VARCHAR2(100 BYTE), 
	"QUANTITE_PRODUIT" NUMBER, 
	"PRIX_PRODUIT" FLOAT(126)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SEANCES
--------------------------------------------------------

  CREATE TABLE "ARIJ"."SEANCES" 
   (	"ID_SALLE" NUMBER, 
	"NUM_SALLE" NUMBER, 
	"ID_EMPLOYE" NUMBER, 
	"CAPACITE_SALLE" NUMBER, 
	"TITRE_COURS" VARCHAR2(255 BYTE), 
	"DATE_SEANCE" DATE, 
	"NIVEAU_SEANCE" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TICKET
--------------------------------------------------------

  CREATE TABLE "ARIJ"."TICKET" 
   (	"ID_TICKET" NUMBER, 
	"ID_EVENEMENT" VARCHAR2(20 BYTE), 
	"TYPE_ACHETEUR" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"PRIX" NUMBER, 
	"DATE_ACHAT" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into ARIJ.ABONNES
SET DEFINE OFF;
REM INSERTING into ARIJ.BIBLIOTHEQUE
SET DEFINE OFF;
REM INSERTING into ARIJ.COMMANDE
SET DEFINE OFF;
REM INSERTING into ARIJ.CONGE
SET DEFINE OFF;
REM INSERTING into ARIJ.EMPLOYE
SET DEFINE OFF;
REM INSERTING into ARIJ.EVENEMENT
SET DEFINE OFF;
REM INSERTING into ARIJ.FACTURES
SET DEFINE OFF;
Insert into ARIJ.FACTURES (ID_FACTURE,ID_FOURNISSEUR_FACTURE,TOTAL_FACTURE,ID_PRODUIT_FACTURE,DATE_FACTURE,ETAT_FACTURE,QUANTITE_FACTURE) values ('2','1','2','2',to_date('01/01/22','DD/MM/RR'),'oui','2');
Insert into ARIJ.FACTURES (ID_FACTURE,ID_FOURNISSEUR_FACTURE,TOTAL_FACTURE,ID_PRODUIT_FACTURE,DATE_FACTURE,ETAT_FACTURE,QUANTITE_FACTURE) values ('3','1','3','3',to_date('01/01/22','DD/MM/RR'),'oui','3');
Insert into ARIJ.FACTURES (ID_FACTURE,ID_FOURNISSEUR_FACTURE,TOTAL_FACTURE,ID_PRODUIT_FACTURE,DATE_FACTURE,ETAT_FACTURE,QUANTITE_FACTURE) values ('1','1','1','2',to_date('01/01/22','DD/MM/RR'),'non','1');
Insert into ARIJ.FACTURES (ID_FACTURE,ID_FOURNISSEUR_FACTURE,TOTAL_FACTURE,ID_PRODUIT_FACTURE,DATE_FACTURE,ETAT_FACTURE,QUANTITE_FACTURE) values ('4','1','4','2',to_date('01/01/22','DD/MM/RR'),'oui','4');
REM INSERTING into ARIJ.FOURNISSEURS
SET DEFINE OFF;
Insert into ARIJ.FOURNISSEURS (ID_FOURNISSEUR,NOM_FOURNISSEUR,ADRESSE_FOURNISSEUR,TELEPHONE_FOURNISSEUR,EMAIL_FOURNISSEUR) values ('1','arij','ariana','00000000','aaaa@gmail.com');
Insert into ARIJ.FOURNISSEURS (ID_FOURNISSEUR,NOM_FOURNISSEUR,ADRESSE_FOURNISSEUR,TELEPHONE_FOURNISSEUR,EMAIL_FOURNISSEUR) values ('2','2','2','33333333','22@gmail.com');
Insert into ARIJ.FOURNISSEURS (ID_FOURNISSEUR,NOM_FOURNISSEUR,ADRESSE_FOURNISSEUR,TELEPHONE_FOURNISSEUR,EMAIL_FOURNISSEUR) values ('3','2','2','33333333','22@gmail.com');
REM INSERTING into ARIJ.HISTORIQUE
SET DEFINE OFF;
REM INSERTING into ARIJ.JOUEURS
SET DEFINE OFF;
REM INSERTING into ARIJ.PARTIES
SET DEFINE OFF;
REM INSERTING into ARIJ.PRODUITS
SET DEFINE OFF;
Insert into ARIJ.PRODUITS (ID_PRODUIT,NOM_PRODUIT,QUANTITE_PRODUIT,PRIX_PRODUIT) values ('3','1','4','1');
Insert into ARIJ.PRODUITS (ID_PRODUIT,NOM_PRODUIT,QUANTITE_PRODUIT,PRIX_PRODUIT) values ('2','4','1','1');
REM INSERTING into ARIJ.SEANCES
SET DEFINE OFF;
REM INSERTING into ARIJ.TICKET
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index ABONNES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ARIJ"."ABONNES_PK" ON "ARIJ"."ABONNES" ("CIN_ABONNES") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EVENEMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ARIJ"."EVENEMENT_PK" ON "ARIJ"."EVENEMENT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index FACTURES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ARIJ"."FACTURES_PK" ON "ARIJ"."FACTURES" ("ID_FACTURE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index FOURNISSEURS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ARIJ"."FOURNISSEURS_PK" ON "ARIJ"."FOURNISSEURS" ("ID_FOURNISSEUR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index JOUEURS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ARIJ"."JOUEURS_PK" ON "ARIJ"."JOUEURS" ("ID_JOUEUR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PARTIES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ARIJ"."PARTIES_PK" ON "ARIJ"."PARTIES" ("ID_PARTIE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PRODUITS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ARIJ"."PRODUITS_PK" ON "ARIJ"."PRODUITS" ("ID_PRODUIT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SEANCES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ARIJ"."SEANCES_PK" ON "ARIJ"."SEANCES" ("ID_SALLE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TICKET_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ARIJ"."TICKET_PK" ON "ARIJ"."TICKET" ("ID_TICKET") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table ABONNES
--------------------------------------------------------

  ALTER TABLE "ARIJ"."ABONNES" ADD CONSTRAINT "ABONNES_PK" PRIMARY KEY ("CIN_ABONNES")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "ARIJ"."ABONNES" MODIFY ("CIN_ABONNES" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EVENEMENT
--------------------------------------------------------

  ALTER TABLE "ARIJ"."EVENEMENT" ADD CONSTRAINT "EVENEMENT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "ARIJ"."EVENEMENT" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FACTURES
--------------------------------------------------------

  ALTER TABLE "ARIJ"."FACTURES" ADD CONSTRAINT "FACTURES_PK" PRIMARY KEY ("ID_FACTURE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "ARIJ"."FACTURES" MODIFY ("ID_FACTURE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FOURNISSEURS
--------------------------------------------------------

  ALTER TABLE "ARIJ"."FOURNISSEURS" ADD CONSTRAINT "FOURNISSEURS_PK" PRIMARY KEY ("ID_FOURNISSEUR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "ARIJ"."FOURNISSEURS" MODIFY ("ID_FOURNISSEUR" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table JOUEURS
--------------------------------------------------------

  ALTER TABLE "ARIJ"."JOUEURS" ADD CONSTRAINT "JOUEURS_PK" PRIMARY KEY ("ID_JOUEUR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "ARIJ"."JOUEURS" MODIFY ("ID_JOUEUR" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PARTIES
--------------------------------------------------------

  ALTER TABLE "ARIJ"."PARTIES" ADD CONSTRAINT "PARTIES_PK" PRIMARY KEY ("ID_PARTIE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "ARIJ"."PARTIES" MODIFY ("ID_PARTIE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRODUITS
--------------------------------------------------------

  ALTER TABLE "ARIJ"."PRODUITS" ADD CONSTRAINT "PRODUITS_PK" PRIMARY KEY ("ID_PRODUIT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "ARIJ"."PRODUITS" MODIFY ("ID_PRODUIT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SEANCES
--------------------------------------------------------

  ALTER TABLE "ARIJ"."SEANCES" ADD CONSTRAINT "SEANCES_PK" PRIMARY KEY ("ID_SALLE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "ARIJ"."SEANCES" MODIFY ("ID_SALLE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TICKET
--------------------------------------------------------

  ALTER TABLE "ARIJ"."TICKET" MODIFY ("ID_TICKET" NOT NULL ENABLE);
 
  ALTER TABLE "ARIJ"."TICKET" ADD CONSTRAINT "TICKET_PK" PRIMARY KEY ("ID_TICKET")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FACTURES
--------------------------------------------------------

  ALTER TABLE "ARIJ"."FACTURES" ADD CONSTRAINT "FACTURES_FK1" FOREIGN KEY ("ID_PRODUIT_FACTURE")
	  REFERENCES "ARIJ"."PRODUITS" ("ID_PRODUIT") ENABLE;
 
  ALTER TABLE "ARIJ"."FACTURES" ADD CONSTRAINT "FACTURES_FK2" FOREIGN KEY ("ID_FOURNISSEUR_FACTURE")
	  REFERENCES "ARIJ"."FOURNISSEURS" ("ID_FOURNISSEUR") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PARTIES
--------------------------------------------------------

  ALTER TABLE "ARIJ"."PARTIES" ADD CONSTRAINT "PARTIES_FK1" FOREIGN KEY ("ID_NOIR")
	  REFERENCES "ARIJ"."JOUEURS" ("ID_JOUEUR") ENABLE;
 
  ALTER TABLE "ARIJ"."PARTIES" ADD CONSTRAINT "PARTIES_FK2" FOREIGN KEY ("ID_BLANC")
	  REFERENCES "ARIJ"."JOUEURS" ("ID_JOUEUR") ENABLE;
